<?xml version="1.0" encoding="utf-8"?>
<Project>
  <PropertyGroup>
    <SolutionDir Condition=" '$(SolutionDir)' == '' ">$([MSBuild]::GetDirectoryNameOfFileAbove($(MSBuildProjectDirectory), atin.slnx))\</SolutionDir>

    <BaseOutputPath>..\..\asm\$(MSBuildProjectName)\bin\</BaseOutputPath>
    <BaseIntermediateOutputPath>..\..\asm\$(MSBuildProjectName)\obj\</BaseIntermediateOutputPath>

    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AnalysisLevel>latest-recommended</AnalysisLevel>
    <EnforceCodeStyleInBuild>true</EnforceCodeStyleInBuild>
    <Deterministic>true</Deterministic>
    <ContinuousIntegrationBuild Condition="'$(GITHUB_ACTIONS)' == 'true'">true</ContinuousIntegrationBuild>
  </PropertyGroup>
</Project>
